apiVersion: v1
kind: Pod
metadata:
  name: div-echoserver-pod-configmap
  labels:
      app: div-echoserver-pod-app
spec:
  containers:
  - image: k8s.gcr.io/echoserver:1.4
    name: div-echoserver-pod
    envFrom:
      - configMapRef:
          name: div-app-config3
