apiVersion: v1
kind: ReplicationController
metadata:
  name: div-echoserver-rc
spec:
  replicas: 3
  template:
    metadata:
      name: div-echoserver-pod
      labels:
        app: div-echoserver-pod-app
    spec:
      containers:
        - image: k8s.gcr.io/echoserver:1.4
          name: div-echoserver-pod
          ports:
            - containerPort: 8080
